// ─── CATALOG DATA ───
const CAT = [
  {id:'consumables',label:'Lab Consumables',icon:'flask',
   items:['Laboratory Glassware & Sample Storage Vials','Plasticwares & Rubberwares','Metal wares, Crucibles & Dishes','Filter Papers — All Grades','Membrane Filters','Syringe Filters','Rubber Wares']},
  {id:'filtration',label:'Filtration Systems',icon:'filter',
   items:['Vacuum Filtration Manifolds 1/3/6 Channel (SS316) with Vacuum Pump','Membrane Filter Holders','Filtration Manifold with Inbuilt Pump — GMP Model','Wound Filter Cartridges']},
  {id:'lamps',label:'Analytical Lamps',icon:'sun',
   items:['Deuterium (D2) Lamps — Agilent, Shimadzu, Waters, Thermo Fisher, JASCO','Hollow Cathode Lamps for AAS','UV Lamps for Spectrophotometer','UV Lamps for UV Chamber / Cabinet','Waste Solvent Collection System PP — 5/10/20L']},
  {id:'hplc',label:'HPLC / GC & Vials',icon:'bar',
   items:['HPLC Stationary Columns (Polar/Mid Polar/Non-Polar) — AD HOC Scientific','Ad Shell / Core Shell Columns','Ghost Terminators & Security Guard Columns','Preparative Columns','GC Columns','HPLC Vials & Caps — 2ml Clear/Amber','GC Vials — 20ml Clear Round/Flat Bottom','CRM Storage Vials (0.5 to 40ml)']},
  {id:'liquid',label:'Liquid Handling',icon:'droplet',
   items:['Autoclavable Micropipettes — Fixed/Variable Volume','Electronic Pipettes — Single/Multi Channel','Bottle Top Dispensers — Mechanical & Electronic (2.5ml to 100ml)','Electronic Burettes (0.01ml to 99.99ml)','Vacuum Controlled Aspiration System','Peristaltic Pumps']},
  {id:'balances',label:'Weighing Balances',icon:'scale',
   items:['Ultra-Micro, Micro & Semi-Micro Balances','Analytical Balances','Precision Balances','Moisture Analyzers','Industrial Scale Balances','Flame Proof Weighing Balances','Anti-Vibration Tables & Pads','Calibrated Test Weights — E1, E2, F1, F2']},
  {id:'heaters',label:'Heaters & Stirrers',icon:'flame',
   items:['Dry Block Heaters — Heating / Heating+Cooling / Heating+Cooling+Mixing','Stirrers Analog/Digital (2500 RPM)','Hot Plates Analog/Digital (500°C)','Hot Plate with Magnetic Stirrer','Multi-Position Stirrer (5/10/15 positions)','Overhead Stirrer (10/20/40/50L)','Heating Mantles (250ml to 5L)','Digital Oil Baths (250ml to 10L)']},
  {id:'baths',label:'Baths & Sonicators',icon:'waves',
   items:['Water Baths Static (6 to 48L)','Circulating & Shaking Water Baths','Ultra-Sonic Baths (2.5 to 24L)','Refrigerated Circulating Bath / Chiller','Refrigerated & Heating Circulating Baths (-20°C to 100°C)','Probe Sonicators (500ml/700ml/1L, Probes 2 to 22mm)']},
  {id:'shakers',label:'Shakers & Rockers',icon:'refresh',
   items:['Orbital Shakers — Single/Double Decker','Linear Shakers','3D Rockers / Gel Rockers','Incubator Shakers — Cooling & Heating','Stackable Incubator Shakers']},
  {id:'centrifuges',label:'Centrifuges & Vortex',icon:'circle',
   items:['Mini Spin & Micro Centrifuges (6K & 8K RPM)','Clinical Centrifuge (4500 RPM)','Laboratory Centrifuges (6K/10K/15K/20K RPM)','Refrigerated Centrifuges (-10°C / -20°C)','High Volume Centrifuges','Vortex Mixer — Analog/Digital, Single/Multi Position']},
  {id:'grinding',label:'Grinding & Milling',icon:'settings',
   items:['Mortar Grinder','Ultra-Centrifugal Mill','Ball Mills & Planetary Ball Mills','Cryogenic Grinder / Freezer Mill','Pulverize Machine','Knife Grinding Mill','Homogenizer','Sieve Shaker']},
  {id:'anal_pharm',label:'Pharma Analytical',icon:'pill',
   items:['Melting Point Apparatus (up to 350°C)','KF / Auto Titrator — Convertible Model','Bulk Density Tester','Tap Density Tester','Friability Tester','Media Degasser','Tablet Disintegration Test Apparatus']},
  {id:'meters',label:'Meters & Spectroscopy',icon:'activity',
   items:['pH & Conductivity Meter','Turbidity Meter','TDS, Ion, Salinity, mV/ORP Meters','UV-Vis Spectrophotometer — Single/Double Beam','Refractometer','Polarimeter','Flame Photometer','COD Digester & Analyzer','Dumas Elemental Analyzer — CHNS-O / CN / N']},
  {id:'food_anal',label:'Food & Feed Analysis',icon:'leaf',
   items:['Auto Kjeldahl System — Nitrogen/Protein Analyzer','Dietary Fiber Analyzer','Soxhlet Extractor — Fat Determination (3/6 positions)','Crude Fiber Analyzer — 3/6 positions (Semi & Fully Automated)','Oxitest — Oxidation Stability Reactor','NIR Analyzer (Food & Feed Samples)','Respirometric Sensor System — BOD']},
  {id:'water',label:'Water Purification',icon:'droplets',
   items:['All Glass Water Distillation Units (Single/Double Stage, 2/4L per hour)','All Quartz Water Distillation Unit (1.5/2.5/4/5/10L)','Ultra-Pure Water System (Low TOC/Zero Endotoxin, 20/40/60L per hour)','PP Yarn Wound Filter Cartridge','PP Melt Blown Filter Cartridge','Activated Carbon Block','Filter Housings']},
  {id:'ovens',label:'Ovens & Furnaces',icon:'box',
   items:['Hot Air Ovens (200°/300°C) — 42/90/210/320/500L','Muffle Furnace (2/7/23L) — up to 1000°/1200°/1500°/1700°C','Stability Chambers (120 to 1050L, 20 to 65°C, RH up to 90%)','Vacuum Oven (27/33/45/56L)','Rotary Evaporator (3/5/10/20L)','Walk-in Chambers — Refrigerator/Freezer/Stability/Incubator']},
  {id:'incubators',label:'Autoclaves & Incubators',icon:'thermometer',
   items:['Vertical Autoclaves (25/60/100/160/220L)','BOD Incubator (120/210/320/500/700L)','Bacteriological Incubator (42/90/210/320/500L)','Dual Chamber Units — Refrigerator + Freezer','Lab Refrigerators (120 to 700L, 2 to 8°C)','Freezers (-20°C)']},
  {id:'furniture',label:'Lab Furniture',icon:'layout',
   items:['Fume Hoods — 2ft/4ft/6ft (Fully Customised)','Laminar Airflow — Vertical/Horizontal (2ft/4ft/6ft)','Biosafety Cabinet Class II Type A2, B2 (2ft/4ft/6ft)','Modular Laboratory Workstation — Academic & Research','Modular Laboratory Workstation — Industrial & Testing']},
  {id:'pharma_ss',label:'Pharma SS Products',icon:'tool',
   items:['Scoops SS316 — Closed & Open Type','SS Beakers, Jugs, Jars & Mugs','SS Powder Spoons','SS Platform Trolley — Single/Double/Triple Decker','SS Mopping Trolley','SS Containers & Buckets','SS Chairs & SS Tables','SS Powder Sampler & Liquid Samplers','SS Hosing Pipes']},
  {id:'coating_plating',label:'Coating & Plating',icon:'layers',
   items:['DFT (Dry Film Thickness) Meter','Gloss Meter','Cross Hatch Adhesion Tester','Surface Roughness Tester','XRF Coating Thickness Gauge','Salt Spray Chamber','Pencil Hardness Tester','Viscosity Meter / Cup','Hull Cell Kit','Taber Abraser','Coating Thickness Measurement System']},
  {id:'defence',label:'Defence & Aerospace',icon:'shield',
   items:['Elemental Analyzer (CHNS-O / Dumas)','UV-Vis Spectrophotometer (High Precision)','High Precision Analytical Balance','Environmental Test Chamber (Temp/Humidity)','High-Temperature Muffle Furnace','Stability Chamber (Defence Spec)','Vacuum Oven (High Precision)','Tensile Testing Equipment']},
  {id:'electronics',label:'Electronics',icon:'cpu',
   items:['UV Exposure Cabinet / Chamber','pH & Conductivity Meter (Electronics Grade)','Color Meter / Colorimeter','IR Spectroscopy Setup','Precision Balance (Electronics Grade)','UV-Vis Spectrophotometer','Curing / Drying Oven','Polarimeter','Conductivity Meter']},
  {id:'automobile',label:'Automobile',icon:'truck',
   items:['Viscosity Meter (Automotive Grade)','Sieve Shaker (Particle Analysis)','Muffle Furnace (Ash Content Testing)','Surface Roughness Tester (Automotive)','DFT Coating Meter (Automotive)','Precision Weighing Balance (Automotive)','COD Analyzer (Effluent Testing)','Hardness Tester (Vickers/Brinell)','Flash Point Apparatus']},
];

// ─── PRODUCT IMAGE MAP ───
const PIMG = {
  'Laboratory Glassware & Sample Storage Vials':'images/products/Glasswares.jpg',
  'Plasticwares & Rubberwares':'images/products/Plasticware-products.jpg',
  'Metal wares, Crucibles & Dishes':'images/products/Metal wares.jpg',
  'Filter Papers — All Grades':'images/products/Filter Papers.jpg',
  'Membrane Filters':'images/products/Filter membranes.jpg',
  'Syringe Filters':'images/products/Syringe Filter all.png',
  'Rubber Wares':'images/products/Rubber ware.jpg',
  'Vacuum Filtration Manifolds 1/3/6 Channel (SS316) with Vacuum Pump':'images/products/Filtration Manifold.png',
  'Membrane Filter Holders':'images/products/Filter-holders-products-tif.jpg',
  'Filtration Manifold with Inbuilt Pump — GMP Model':'images/products/Filtration_GMP.jpg',
  'Wound Filter Cartridges':'images/products/Wound Filters.jpg',
  'Deuterium (D2) Lamps — Agilent, Shimadzu, Waters, Thermo Fisher, JASCO':'images/products/Lamp D2.png',
  'Hollow Cathode Lamps for AAS':'images/products/Lamp HCL.jpg',
  'UV Lamps for Spectrophotometer':'images/products/UV lamp.jpg',
  'UV Lamps for UV Chamber / Cabinet':'images/products/UV lamp TLC.jpg',
  'Waste Solvent Collection System PP — 5/10/20L':'images/products/Waste Solvent Collection.jpg',
  'HPLC Stationary Columns (Polar/Mid Polar/Non-Polar) — AD HOC Scientific':'images/products/Column HPLC.png',
  'Ad Shell / Core Shell Columns':'images/products/Column HPLC.png',
  'Ghost Terminators & Security Guard Columns':'images/products/Column HPLC.png',
  'Preparative Columns':'images/products/Columns DAC.jpg',
  'GC Columns':'images/products/Columns GC.png',
  'HPLC Vials & Caps — 2ml Clear/Amber':'images/products/Vials HPLC 2ML-9mm-autosampler-vials-supplier.jpg',
  'GC Vials — 20ml Clear Round/Flat Bottom':'images/products/Vials GC-vials-crimp-cap.jpg',
  'CRM Storage Vials (0.5 to 40ml)':'images/products/CRM Storage Vials.jpg',
  'Autoclavable Micropipettes — Fixed/Variable Volume':'images/products/LHS Micripipet.png',
  'Electronic Pipettes — Single/Multi Channel':'images/products/LHS Electronic-Micropipette.jpg',
  'Bottle Top Dispensers — Mechanical & Electronic (2.5ml to 100ml)':'images/products/LHS DispensMate-Pro__578764734.jpg',
  'Electronic Burettes (0.01ml to 99.99ml)':'images/products/LHS Electronic burette.jpg',
  'Vacuum Controlled Aspiration System':'images/products/LHS Aspiration System.jpg',
  'Peristaltic Pumps':'images/products/Peristaltic Pump.jpg',
  'Ultra-Micro, Micro & Semi-Micro Balances':'images/products/Weighing Micro Balance.jpg',
  'Analytical Balances':'images/products/Weighing Analytical Balance.jpg',
  'Precision Balances':'images/products/Weighing Top Pan Balance.jpg',
  'Moisture Analyzers':'images/products/Weighing Moisture Balalnce.jpg',
  'Industrial Scale Balances':'images/products/Weighing Platform Balalnce.jpg',
  'Flame Proof Weighing Balances':'images/products/Weighing Flame-Proof.jpg',
  'Anti-Vibration Tables & Pads':'images/products/Weighing Standard anti-vibration table.jpg',
  'Calibrated Test Weights — E1, E2, F1, F2':'images/products/Weighing Std Weights.jpg',
  'Dry Block Heaters — Heating / Heating+Cooling / Heating+Cooling+Mixing':'images/products/Dry Block heater.jpg',
  'Stirrers Analog/Digital (2500 RPM)':'images/products/Magnetic stirrer.jpg',
  'Hot Plates Analog/Digital (500°C)':'images/products/Hot-Plate-Magnetic-Stirrer.jpg',
  'Hot Plate with Magnetic Stirrer':'images/products/Hot-Plate-Magnetic-Stirrer.jpg',
  'Multi-Position Stirrer (5/10/15 positions)':'images/products/Multi Position Stirrer.jpg',
  'Overhead Stirrer (10/20/40/50L)':'images/products/Overhead Stirrer.jpg',
  'Heating Mantles (250ml to 5L)':'images/products/Heating mantle.png',
  'Digital Oil Baths (250ml to 10L)':'images/products/Oil bath.jpg',
  'Water Baths Static (6 to 48L)':'images/products/Water bath.jpg',
  'Circulating & Shaking Water Baths':'images/products/Water bath Shaking & Stirring.jpg',
  'Ultra-Sonic Baths (2.5 to 24L)':'images/products/Sonicator.jpg',
  'Refrigerated Circulating Bath / Chiller':'images/products/Chiller.jpg',
  'Refrigerated & Heating Circulating Baths (-20°C to 100°C)':'images/products/Chiller.jpg',
  'Probe Sonicators (500ml/700ml/1L, Probes 2 to 22mm)':'images/products/Sonicator.jpg',
  'Orbital Shakers — Single/Double Decker':'images/products/Shaker-SK-0330-Pro.jpg',
  'Linear Shakers':'images/products/Shaker-SK-0330-Pro.jpg',
  '3D Rockers / Gel Rockers':'images/products/3D Shaker Gel rocker.jpg',
  'Incubator Shakers — Cooling & Heating':'images/products/Shaker Incubatoer-shaker-1-.jpg',
  'Stackable Incubator Shakers':'images/products/Stackable Incubator shaker.jpg',
  'Mini Spin & Micro Centrifuges (6K & 8K RPM)':'images/products/Centrifuge mini.jpg',
  'Clinical Centrifuge (4500 RPM)':'images/products/Centrifuge Clinical.png',
  'Laboratory Centrifuges (6K/10K/15K/20K RPM)':'images/products/Centrifuge.jpg',
  'Refrigerated Centrifuges (-10°C / -20°C)':'images/products/Centrifuge refrigerated.jpg',
  'High Volume Centrifuges':'images/products/Centrifuge floor model.jpg',
  'Vortex Mixer — Analog/Digital, Single/Multi Position':'images/products/Vortex-Mixer.jpg',
  'Mortar Grinder':'images/products/Mortor Grinder.jpg',
  'Ultra-Centrifugal Mill':'images/products/Centrifugal Mill.jpg',
  'Ball Mills & Planetary Ball Mills':'images/products/Planetary ball mill.jpg',
  'Cryogenic Grinder / Freezer Mill':'images/products/Cryo mill.jpg',
  'Pulverize Machine':'images/products/pulveriser-Laarman-2019.jpg',
  'Knife Grinding Mill':'images/products/knife Cutter.png',
  'Homogenizer':'images/products/Homogenizer hand held.png',
  'Sieve Shaker':'images/products/Sieve Shaker.jpg',
  'Melting Point Apparatus (up to 350°C)':'images/products/Melting-Point-Apparatus-EMA-4M.jpg',
  'KF / Auto Titrator — Convertible Model':'images/products/Auto-titrator-Convertible KF Titrator-903.jpg',
  'Bulk Density Tester':'images/products/BULK-DENSITY-TESTERVOLUMETER-iSmartBT-2001i.png',
  'Tap Density Tester':'images/products/TAP-DENSITY-TESTER-1219.png',
  'Friability Tester':'images/products/Friablity-Tester-QFR-200.png',
  'Media Degasser':'images/products/DISSOLUTION-MEDIA-DEGASSER2.png',
  'Tablet Disintegration Test Apparatus':'images/products/DISINTEGRATION-TESTER--QD-200.png',
  'pH & Conductivity Meter':'images/products/pH meter_ Condusctivity_ TDS_ ORP.jpg',
  'Turbidity Meter':'images/products/Turbidity meter.jpg',
  'TDS, Ion, Salinity, mV/ORP Meters':'images/products/pH meter_ Condusctivity_ TDS_ ORP.jpg',
  'UV-Vis Spectrophotometer — Single/Double Beam':'images/products/uv-vis-double-beam-spectrophotometer.jpg',
  'Refractometer':'images/products/Refractometer.jpg',
  'Polarimeter':'images/products/polarimeter-with-21cfr-compliance-adp100cfr.png',
  'Flame Photometer':'images/products/Flame-photometer.jpg',
  'COD Digester & Analyzer':'images/products/cod-analyzer-with-digester.png',
  'Dumas Elemental Analyzer — CHNS-O / CN / N':'images/products/Elemental Analyzer_CN.jpg',
  'Auto Kjeldahl System — Nitrogen/Protein Analyzer':'images/products/Kjeldahl Nitrogen Analyzer.png',
  'Dietary Fiber Analyzer':'images/products/Dietary Fiber Analyzer.jpg',
  'Soxhlet Extractor — Fat Determination (3/6 positions)':'images/products/Solvent Extractor.jpg',
  'Crude Fiber Analyzer — 3/6 positions (Semi & Fully Automated)':'images/products/Fiber Analyzer.jpg',
  'Oxitest — Oxidation Stability Reactor':'images/products/OXITEST-310203.jpg',
  'NIR Analyzer (Food & Feed Samples)':'images/products/spectraalyzer-zeutec-gmbh-nir-spectroscopy.jpg',
  'Respirometric Sensor System — BOD':'images/products/RESPIROMETRIC Sensor system 6_BOD-310234.jpg',
  'All Glass Water Distillation Units (Single/Double Stage, 2/4L per hour)':'images/products/Distillation unit Glass.jpg',
  'All Quartz Water Distillation Unit (1.5/2.5/4/5/10L)':'images/products/Distillation Unit Quartz.png',
  'Ultra-Pure Water System (Low TOC/Zero Endotoxin, 20/40/60L per hour)':'images/products/Ultra Pure Water system.png',
  'PP Yarn Wound Filter Cartridge':'images/products/string-wound-filter-cartridges1.jpg',
  'PP Melt Blown Filter Cartridge':'images/products/spun-cartridge-filter.png',
  'Activated Carbon Block':'images/products/Activated Carbon Filter.jpg',
  'Filter Housings':'images/products/Housing-filter-for-domestic-ro-water-purifier.jpg',
  'Hot Air Ovens (200°/300°C) — 42/90/210/320/500L':'images/products/Hot Air Oven.jpg',
  'Muffle Furnace (2/7/23L) — up to 1000°/1200°/1500°/1700°C':'images/products/Muffle Furnace.jpg',
  'Stability Chambers (120 to 1050L, 20 to 65°C, RH up to 90%)':'images/products/Stability Chamber.jpg',
  'Vacuum Oven (27/33/45/56L)':'images/products/Vacuum Oven.jpg',
  'Rotary Evaporator (3/5/10/20L)':'images/products/Rotary Evaporator.jpg',
  'Walk-in Chambers — Refrigerator/Freezer/Stability/Incubator':'images/products/walk-in-chambers-04.jpg',
  'Vertical Autoclaves (25/60/100/160/220L)':'images/products/Autoclave.jpg',
  'BOD Incubator (120/210/320/500/700L)':'images/products/BOD Incubator.jpg',
  'Bacteriological Incubator (42/90/210/320/500L)':'images/products/Incubator.jpg',
  'Dual Chamber Units — Refrigerator + Freezer':'images/products/Dual Chamber Refr_Freezer.jpg',
  'Lab Refrigerators (120 to 700L, 2 to 8°C)':'images/products/Refrigerator.jpg',
  'Freezers (-20°C)':'images/products/Freezer.jpg',
  'Fume Hoods — 2ft/4ft/6ft (Fully Customised)':'images/products/Fume hood.jpeg',
  'Laminar Airflow — Vertical/Horizontal (2ft/4ft/6ft)':'images/products/Laminar Air flow.jpeg',
  'Biosafety Cabinet Class II Type A2, B2 (2ft/4ft/6ft)':'images/products/Biosafety Cabinet.jpeg',
  'Modular Laboratory Workstation — Academic & Research':'images/products/Lab Interior.png',
  'Modular Laboratory Workstation — Industrial & Testing':'images/products/Lab Interior CAD Diagram.jpg',
  'Scoops SS316 — Closed & Open Type':'images/products/stainless-steel-open-scoops.jpg',
  'SS Beakers, Jugs, Jars & Mugs':'images/products/ss-beaker-jug-jar-mug-medium-for-pharma.jpg',
  'SS Powder Spoons':'images/products/SS Charis.jpg',
  'SS Platform Trolley — Single/Double/Triple Decker':'images/products/SS Trolley.jpg',
  'SS Mopping Trolley':'images/products/ss-mopping-trolley-500x500.jpg',
  'SS Containers & Buckets':'images/products/SS Buckets.jpg',
  'SS Chairs & SS Tables':'images/products/SS Tables.jpg',
  'SS Powder Sampler & Liquid Samplers':'images/products/ss-liquid-sampler.jpg',
  'SS Hosing Pipes':'images/products/SS hose-pipe.jpg',
  'DFT (Dry Film Thickness) Meter':'images/products/DFT Coating Meter.png',
  'Gloss Meter':'images/products/Gloss Meter.png',
  'Cross Hatch Adhesion Tester':'images/products/Cross Hatch Test.png',
  'Surface Roughness Tester':'images/products/Surface Roughness.png',
  'XRF Coating Thickness Gauge':'images/products/XRF Thickness Gauge.png',
  'Salt Spray Chamber':'images/products/Salt Spray Chamber.png',
  'Pencil Hardness Tester':'images/products/Hardness Test.png',
  'Viscosity Meter / Cup':'images/products/Viscosity Meter.png',
  'Hull Cell Kit':'images/products/Hull Test Kit.png',
  'Taber Abraser':'images/products/Taber Abraser.jpeg',
  'Coating Thickness Measurement System':'images/products/Coating Thickness Files.jpeg',
  'Elemental Analyzer (CHNS-O / Dumas)':'images/products/Elementle Analyzer_CHNSO.jpg',
  'UV-Vis Spectrophotometer (High Precision)':'images/products/uv-vis-double-beam-spectrophotometer.jpg',
  'High Precision Analytical Balance':'images/products/Weighing analytical-balance.jpg',
  'Environmental Test Chamber (Temp/Humidity)':'images/products/Drying Chamber.png',
  'High-Temperature Muffle Furnace':'images/products/Muffle Furnace.jpg',
  'Stability Chamber (Defence Spec)':'images/products/Stability_PT_kazo3n_xtc6zf.png',
  'Vacuum Oven (High Precision)':'images/products/Vacuum Oven.jpg',
  'Tensile Testing Equipment':'images/products/Hardness Test.png',
  'UV Exposure Cabinet / Chamber':'images/products/UV Chamber.png',
  'pH & Conductivity Meter (Electronics Grade)':'images/products/Conductvity Meter.png',
  'Color Meter / Colorimeter':'images/products/Color Meter.png',
  'IR Spectroscopy Setup':'images/products/IR Setup.png',
  'Precision Balance (Electronics Grade)':'images/products/Weighing Machine.png',
  'UV-Vis Spectrophotometer':'images/products/Spectophotometer.png',
  'Curing / Drying Oven':'images/products/Lab Oven.png',
  'Polarimeter':'images/products/Polarimeter.png',
  'Conductivity Meter':'images/products/Conductvity Meter.png',
  'Viscosity Meter (Automotive Grade)':'images/products/Viscosity Meter.png',
  'Sieve Shaker (Particle Analysis)':'images/products/Sieve Analysis.png',
  'Muffle Furnace (Ash Content Testing)':'images/products/Muffle Furnace.jpg',
  'Surface Roughness Tester (Automotive)':'images/products/Surface Roughness.png',
  'DFT Coating Meter (Automotive)':'images/products/DFT Meter.png',
  'Precision Weighing Balance (Automotive)':'images/products/Weighing Scale.png',
  'COD Analyzer (Effluent Testing)':'images/products/cod-analyzer-with-digester.png',
  'Hardness Tester (Vickers/Brinell)':'images/products/Hardness Test.png',
  'Flash Point Apparatus':'images/products/Lab Oven.png',
};

// ─── BRANDS ───
const BRANDS_ROW1 = [
  {name:'Supertek',          img:'images/brands/brand_image40.jpeg'},
  {name:'Mettler Toledo',    img:'images/brands/brand_image41.png'},
  {name:'Sartorius',         img:'images/brands/brand_image42.jpeg'},
  {name:'Hanna Instruments', img:'images/brands/brand_image43.png'},
  {name:'Zeiss',             img:'images/brands/brand_image44.png'},
  {name:'Laarmann',          img:'images/brands/brand_image45.png'},
  {name:'DAN Logitech',      img:'images/brands/brand_image46.png'},
  {name:'Aczel',             img:'images/brands/brand_image47.png'},
  {name:'Fisher Scientific', img:'images/brands/brand_image48.png'},
];
const BRANDS_ROW2 = [
  {name:'3nh',      img:'images/brands/brand_image49.png'},
  {name:'QNix',     img:'images/brands/brand_image50.png'},
  {name:'Mitutoyo', img:'images/brands/brand_image51.png'},
  {name:'Labman',   img:'images/brands/brand_image52.png'},
  {name:'Velp',     img:'images/brands/brand_image53.png'},
  {name:'Kewaunee', img:'images/brands/brand_image54.png'},
  {name:'Asecos',   img:'images/brands/brand_image55.png'},
  {name:'QLS',      img:'images/brands/brand_image56.png'},
];

// ─── HOME CATEGORY CARDS ───
const HOME_CATS = [
  {title:'Lab Consumables',desc:'Glassware, plasticware, filter papers, membranes, syringe filters and sample storage vials.',img:'images/products/Glasswares.jpg'},
  {title:'Analytical Instruments',desc:'HPLC columns, UV-Vis spectrophotometers, KF titrators, COD analyzers and elemental analyzers.',img:'images/products/uv-vis-double-beam-spectrophotometer.jpg'},
  {title:'Weighing Balances',desc:'Ultra-micro to industrial scales, moisture analyzers, flame-proof balances and calibrated test weights.',img:'images/products/Weighing Analytical Balance.jpg'},
  {title:'Bench Top Equipment',desc:'Centrifuges, shakers, stirrers, hot plates, sonicators, water baths and grinding mills.',img:'images/products/Centrifuge.jpg'},
  {title:'Process Instruments',desc:'Hot air ovens, muffle furnaces, stability chambers, autoclaves and rotary evaporators.',img:'images/products/Stability Chamber.jpg'},
  {title:'Lab Furniture & SS',desc:'Fume hoods, laminar airflows, biosafety cabinets, modular workstations and pharma SS-316 products.',img:'images/products/Fume hood.jpeg'},
];

// ─── MARQUEE ITEMS ───
const MQ_ITEMS = ['Laboratory Consumables','Analytical Instruments','HPLC Columns','Weighing Balances','Centrifuges','Process Instruments','Laboratory Furniture','Pharma SS Products','Coating & Plating','Defence & Aerospace','Electronics','Automobile','GeM Registered','Export & Import'];

// ─── ESTEEMED CUSTOMERS (Slide 11) ───
const CUSTOMERS = [
  { name:'Micro Labs',                   initials:'ML',   sector:'Pharma',        color:'#651b45' },
  { name:'Apotex Pharma Chem',           initials:'APC',  sector:'Pharma',        color:'#065A82' },
  { name:'Himalaya Wellness',            initials:'HW',   sector:'Life Sciences', color:'#2C5F2D' },
  { name:'Reliance Life Sciences',       initials:'RLS',  sector:'Pharma',        color:'#B85042' },
  { name:'ITC Life Sciences',            initials:'ITC',  sector:'FMCG',          color:'#028090' },
  { name:'Lifeline Feeds',              initials:'LF',   sector:'Food & Feed',   color:'#6D2E46' },
  { name:'Medreich Ltd',                initials:'MR',   sector:'Pharma',        color:'#36454F' },
  { name:'Anthem Biosciences',          initials:'AB',   sector:'Biotech',       color:'#7B3F9E' },
  { name:'Indian Institute of Science', initials:'IISc', sector:'Research',      color:'#1A5276' },
  { name:'MTR Foods',                   initials:'MTR',  sector:'Food Industry', color:'#943126' },
];
